### ISSUE TITLE
Exclude given files

### ISSUE THREAD

**Issue by LeoHuckvale** [PyCQA/pydocstyle#186]
It would be useful to be able to exclude given files, in the same manner as [flake8](http://flake8.readthedocs.io/), e.g.:

    pydocstyle --exclude docs/*,idl_generated_protocol.py

**Comment by sigmavirus24** [comment]
@LeoHuckvale if you use flake8 + a plugin (flake8-docstrings or flake8-pep257) to also run pydocstyle within flake8, then flake8's `--exclude` will work for you.

**Comment by LeoHuckvale** [comment]
Thanks, much appreciated. I still think it would be a useful feature in pydocstyle if, for example, you wanted to PEP8 your tests to make sure they're readable, but not demand that they have docstrings.

**Comment by jayvdb** [comment]
> PEP8 your tests to make sure they're readable, but not demand that they have docstrings.

flake8 can do that.  flake8 is a front-end for pyflakes + pep8, and any other plugins you want to install.  And the pyflakes rules can be easily disabled, if you just want flake8 to only rule pep8 rules.

Note that all of the logic to exclude files is already in `pydocstyle`, if you want to create your own pep8 front-end.  But `flake8` already provides a more complex front-end for `pydocstyle` with more advanced command line arguments, plugins, etc.  I suspect that the maintainers of `pydocstyle` want to focus on the rules, and let `flake8` support user needs regarding to the command line interface.

If you have two distinct sets of rules for files in distinct directories, such as `<package>/` vs `tests/`, you could invoke pep8 or flake8 twice, one for each directory, with different arguments.

If you want to do it in one command, and have more complex scenarios such as excluding only some codes from some files, you can use the flake8 plugin `flake8-putty` (note that it doesnt work correctly on Windows atm; the fix for that should land very soon).

**Comment by sigmavirus24** [comment]
Also flake8 3.0 (which is currently under development) will allow for more complex usage of `--select` and `--ignore` which is presently impossible and improbable with flake8 2.x. You can, however, right now do something like:

```
flake8 --ignore D directories/without/docstrings/
flake8 --select D directories/with/docstrings
```

But that's just a suggestion. It's up to @Nurdok what they actually want to do with pydocstyle's CLI.

**Comment by LeoHuckvale** [comment]
Cool, I'll try that. Thanks for your help. :)

**Comment by Nurdok** [comment]
I don't have current plans to implement an `--exclude` flag. The `--match` and `--match-dir` make various configurations possible while `flake8` provides a nice interface.

**Comment by goanpeca** [comment]
Pep8 and flake8 provide a exclude config options as well, it would be nice to have it as well :-|

**Comment by syre** [comment]
I agree, mirroring the exclude config option that `pycodestyle` have would be nice.

**Comment by deavid** [comment]
Using pydocstyle outside of other tools (flake8 or pep8) as we're using different rules/exclude for them.
We would also appreciate having a exclude option.

**Comment by kevin-dimichel-dr** [comment]
I use pydocstyle as a [pre-commit](https://pre-commit.com/) hook.  Since pydocstyle doesn't support an exclude parameter, I ended up using the exclude provided by pre-commit:

```yaml
repos:
  - repo: https://github.com/PyCQA/pydocstyle
    rev: master
    hooks:
      - id: pydocstyle
        exclude: 'FILE_1_TO_EXCLUDE|FILE_2_TO_EXCLUDE'
```

**Comment by MarcoGorelli** [comment]
> I don't have current plans to implement an `--exclude` flag. The `--match` and `--match-dir` make various configurations possible while `flake8` provides a nice interface.

Thanks :+1: For anyone wanting a quick solution:

if you want to exclude the file `foo.py` (in addition to what's already being excluded), you can pass
```
--match='(?!test_|foo).*\.py'
```

**Comment by zillionare** [comment]
this works for me:
```
per-file-ignores = 
    tests/*:D
```
use a per-file-ignores
