### ISSUE TITLE
Separate error for missing docstring on nested (Meta) classes

### ISSUE THREAD

**Issue by hvdklauw** [PyCQA/pydocstyle#198]
In django the usage of a nested Meta class is pretty common, however adding docstrings to those classes is just silly.

Would be nice to have it separated from normal classes so we could turn off the need for a docstring there.

**Comment by jayvdb** [comment]
This issue is about a nested class named `Meta`.
https://docs.djangoproject.com/en/dev/topics/db/models/#meta-options

I doubt special-casing that name is appropiate, although it could be done in conjunction with special casing of the outer-class subclassing `models.Model`, but then we have the problem that the ast cant detect indirect subclassing.

The other approach is a separate error for any nested classes, and probably also nested functions if they are not already a different error or no error.

Any other approaches?

**Comment by hvdklauw** [comment]
I dislike the first option, then soon there will be some other special case somewhere in the python eco system and we'll end up with many lines of code to handle all those special cases.

I think the separate errors for nested classes and for nested functions (2 extra errors) would be much nicer.

**Comment by thejcannon** [comment]
@Nurdok this can be closed, right? As #261 has added D106 for this case?
