### ISSUE TITLE
pydocstyle should not check setup.py

### ISSUE THREAD

**Issue by nbraud** [PyCQA/pydocstyle#322]
pydocstyle, in its default configuration, complains about the `setup.py` file missing a module-level docstring:
```
$ tox
GLOB sdist-make: /home/nicoo/devel/py/emanate/setup.py
docstyle inst-nodeps: /home/nicoo/devel/py/emanate/.tox/dist/emanate-2.0.0.zip
docstyle installed: emanate==2.0.0,pkg-resources==0.0.0,pydocstyle==2.1.1,six==1.11.0,snowballstemmer==1.2.1
docstyle runtests: PYTHONHASHSEED='3374526676'
docstyle runtests: commands[0] | pydocstyle
./setup.py:1 at module level:
        D100: Missing docstring in public module
[...]
```

The tox.ini file didn't contain anything special:
```
[testenv:docstyle]
deps = pydocstyle
commands = pydocstyle
```

I worked around the default behaviour by specifying a single subdirectory to check, but pydocstyle probably shouldn't check setup.py by default.

**Comment by sigmavirus24** [comment]
@nbraud what makes you think that `setup.py` shouldn't be checked? I know people don't tend to include `setup.py` in their project documentation, but including a docstring does not hurt anything.

**Comment by nbraud** [comment]
@sigmavirus24 Which information would the docstring convey?
I don't think there is anything particularly-meaningful to put there, as it would be entirely redundant: “setup.py file for project `foo`” does not actually give the reader more information.

**Comment by shacharoo** [comment]
@nbraud , I agree with @sigmavirus24 . Furthermore:
1. The fact that the project has a file named `setup.py` could be coincidental. There are other build tools available.
2. The file might contain utility functions that do complex things. There's no reason they shouldn't have a docstring.

You might argue that `pydocstyle` should at least not check for a file docstring in that file, but we have no way of excluding a specific file and error code (which, again, isn't something we should do by default due to the 1st reason I wrote above).

Closing for now, but feel free to ping if you think we need to reconsider 👍 

Cheers,
Shachar.
