### ISSUE TITLE
How to exclude functions matching a pattern from D100 error?

### ISSUE THREAD

**Issue by AlexArcPy** [PyCQA/pydocstyle#354]
I have a few functions on a legacy code base named `call` that do not have a docstring. I would like to be able to specify that I do not want to check for docstring presence for the functions named `call`. It would be helpful to have an extra configuration with the whitelist of such functions. Adding `# noqa` comment is not an option. 

Is it something already supported? If not, I would love to see this feature implemented.
Is it something that I could implement relatively easy in the source code for submitting a PR?

**Comment by AlexArcPy** [comment]
@Nurdok thanks for getting back! I gave you just an example of a functionality with a dummy function `call`. The actual code base has dozens scripts which are used as `cli` tools and each has boilerplate functions like `main`, `read_cli_args`, `parse_args` etc. The docstring will be pretty much the same as the function name with whitespaces, so I wondered whether those function names could be whitelisted. Adding `# noqa` takes as much effort as adding a docstring.

Another use case for this would be Python frameworks where you need to override magic dunder methods and adding docstrings for all those `__str__()` seems unnecessary. Does it make sense?

**Comment by Nurdok** [comment]
For magic methods there's a separate error code specifically designed for this common use case. But the main reason we handle that case is that the APIs for these methods is known from their name. That error

In your example, say, `read_cli_args`, I think there's still reason to document the function: does it return a value? In what format? What's the behavior for invalid CLI flags? etc., etc.

If your general opinion is "some constructs do not need docstrings because their name is self-explanatory", you can simply turn off all of the `D1xx` "missing docstring" error codes.

**Comment by AlexArcPy** [comment]
Good points @Nurdok , thanks! I don't want to disable `D1` for the whole file as there are other functions for which I would like to enforce presence of docstrings :) Anyway, I guess I will need to add docstrings to them as this is the only option to me (apart from `# noqa`). Cheers,

**Comment by Nurdok** [comment]
@AlexArcPy that's great. Sorry for the push back, but as with any open source project, each user has their own unique use case and we need to make sure features are applicable to a large portion of them to avoid feature creep and to keep the code maintainable.

Cheers!
