### ISSUE TITLE
Contradictory pep257 warnings

### ISSUE THREAD

**Issue by bje-** [PyCQA/pydocstyle#533]
`pep257` warns:

```
  Line: 15
    pep257: D203 / 1 blank line required before class docstring (found 0)
```

So I correct this by inserting one blank line before my class docstring. Then `pep257` warns:

```
  Line: 16
    pep257: D211 / No blank lines allowed before class docstring (found 1)
```

**Comment by samj1912** [comment]
D203 is explicitly block-listed for all default conventions - https://github.com/PyCQA/pydocstyle/blob/cf29c320beb2bc2f63f6b3e1577291d20839bc33/src/pydocstyle/violations.py#L432

This code exists for b/w compat. You can add it to your ignore list or use a default convention. 

If you want to customize conventions use `add-select` or `add-ignore` instead of `select` or `ignore`

Please have a look at http://www.pydocstyle.org/en/stable/usage.html#command-line-interface
